version: '3.8'

services:
  # Mocked Data source files from this sftp will be csv's
  sftp-partner-1:
    image: atmoz/sftp:latest
    container_name: sftp-partner1
    ports:
      - "2222:22"
    volumes:
      - ./sftp/partner1:/home/csvuser/download
    command: csvuser:password:1000
    # due to issue addressed here https://github.com/atmoz/sftp/issues/341 in case you want to manually sftp into the
    # container you need these lines
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  # Mocked Data source files from this sftp will be Fixed Width Format files
  sftp-partner-2:
    image: atmoz/sftp:latest
    container_name: sftp-partner2
    ports:
      - "2223:22"
    volumes:
      - ./sftp/partner2:/home/fwfuser/download
    command: fwfuser:password

  # To have a local version of AWS service and mock buckets
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
  # to visualize the data
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - metabase-data:/dev/random:ro
    ports:
      - 3001:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: airflow
      MB_DB_PORT: 5432
      MB_DB_USER: airflow
      MB_DB_PASS: airflow
      MB_DB_HOST: postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  minio-data:
  metabase-data:
