[tool.ruff]

# Same as Black's line length
line-length = 100

# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".github",
    "__pycache__",
    "build",
    "dist",
    "venv",
    ".env",
    ".venv",
    "logs",
]

# Assume Python 3.10
target-version = "py310"

[tool.ruff.lint]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
fixable = ["ALL"]

# Ignore specific rules in specific files
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]

# Customize isort behavior to match your previous isort config
[tool.ruff.lint.isort]
known-first-party = ["src"]
known-third-party = ["airflow", "minio"]

# Configure flake8-like rules
[tool.ruff.lint.mccabe]
max-complexity = 25

[tool.ruff.format]
# Use double quotes for docstrings
docstring-code-format = true
quote-style = "double"
# Line ending preferences
line-ending = "auto"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
addopts = "--cov=src --cov=dags --cov-report=term-missing"
markers = [
    "unit: marks tests as unit tests",
    "integration: marks tests as integration tests",
]
