[tool.ruff]
# Enable flake8-bugbear (`B`) rules.
select = ["E", "F", "B", "I", "C", "W"]

# Same as Black's line length
line-length = 100

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
# Allow unused variables when underscore-prefixed.
allow-unused-variables = true

# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".github",
    "__pycache__",
    "build",
    "dist",
    "venv",
    ".env",
    ".venv",
    "logs",
]

# Assume Python 3.10
target-version = "py310"

# Ignore specific rules in specific files
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]  # Ignore unused imports in __init__.py

# Customize isort behavior to match your previous isort config
[tool.ruff.isort]
known-first-party = ["src"]
known-third-party = ["airflow", "minio"]

# Configure flake8-like rules
[tool.ruff.mccabe]
max-complexity = 25  # Matching your updated flake8 max-complexity

[tool.ruff.format]
# Use double quotes for docstrings
docstring-code-format = true
quote-style = "double"
# Line ending preferences
line-ending = "auto"
