[tool.ruff]

# Same as Black's line length
line-length = 100

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".github",
    "__pycache__",
    "build",
    "dist",
    "venv",
    ".env",
    ".venv",
    "logs",
]

# Assume Python 3.10
target-version = "py310"

# Ignore specific rules in specific files
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]

# Customize isort behavior to match your previous isort config
[tool.ruff.isort]
known-first-party = ["src"]
known-third-party = ["airflow", "minio"]

# Configure flake8-like rules
[tool.ruff.mccabe]
max-complexity = 25

[tool.ruff.format]
# Use double quotes for docstrings
docstring-code-format = true
quote-style = "double"
# Line ending preferences
line-ending = "auto"
